[package]
name = "polkadot-statement-table"
version = "0.9.31"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
primitives = { package = "polkadot-primitives", path = "../primitives" }
