[package]
name = "prioritized-metered-channel"
version = "0.2.0"
description = "Channels with built-in observability and message priorizitazion (coming soon™)"
license = "MIT OR Apache-2.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
derive_more = "0.99"
tracing = "0.1.35"
thiserror = "1.0.31"
crossbeam-queue = "0.3.5"
nanorand = { version = "0.7.0", default-features = false, features = ["wyrand"] }
coarsetime = "^0.1.22"

[dev-dependencies]
futures = { version = "0.3.21", features = ["thread-pool"] }
assert_matches = "1.5"
env_logger = "0.9"
log = "0.4"
tracing = { version = "0.1.35", features = ["log"] }
