[package]
name = "polkadot-client"
version = "0.9.31"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
frame-benchmarking = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
frame-system = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
futures = { version = "0.3.21", features = ["thread-pool"] }

sp-consensus = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sp-storage = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sp-runtime = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sp-api = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sp-core = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sp-keyring = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sp-inherents = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sp-session = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sp-offchain = { package = "sp-offchain", git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sp-mmr-primitives = { git = "https://github.com/paritytech/substrate", default-features = false , " branch" = "alexg/reduce_provisioner_work_v2" }

sc-consensus = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sc-executor = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sc-client-api = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }
sc-service = { git = "https://github.com/paritytech/substrate", default-features = false , " branch" = "alexg/reduce_provisioner_work_v2" }

beefy-primitives = { git = "https://github.com/paritytech/substrate", " branch" = "alexg/reduce_provisioner_work_v2" }

# Polkadot Runtimes
polkadot-runtime = { path = "../../runtime/polkadot", optional = true }
kusama-runtime = { path = "../../runtime/kusama", optional = true }
westend-runtime = { path = "../../runtime/westend", optional = true }
rococo-runtime = { path = "../../runtime/rococo", optional = true }

polkadot-core-primitives = { path = "../../core-primitives" }
polkadot-primitives = { path = "../../primitives" }
polkadot-node-core-parachains-inherent = { path = "../core/parachains-inherent" }
polkadot-runtime-common = { path = "../../runtime/common" }

[features]
default = ["polkadot"]
polkadot = ["polkadot-runtime"]
kusama = ["kusama-runtime"]
rococo = ["rococo-runtime"]
westend = ["westend-runtime"]
runtime-metrics = [
    "rococo-runtime/runtime-metrics",
    "kusama-runtime/runtime-metrics",
    "westend-runtime/runtime-metrics",
    "polkadot-runtime/runtime-metrics",
]
